language: php

php:
  - 5.4
  - 5.5

mysql:
  database: starterkit
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running a web server from drush on php 5.4
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # add composer's global bin directory to the path
  # see: https://github.com/drush-ops/drush#install---composer
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc

  # install drush globally
  - composer global require drush/drush:6.*

script:

  # create a new database
  - mysql -e 'CREATE DATABASE starterkit'

  # build the distribution using Drush make.
  - drush make --prepare-install make/ucsf_installprofile.make webroot

  - cd webroot

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes site-install --profile=ucsf_installprofile --no-server --db-url=mysql://root:@127.0.0.1/starterkit

  # start a web server on port 8080, run in the background; wait for initialization to complete.
  - drush runserver 127.0.0.1:8888 &
  - until netstat -an 2>/dev/null | grep '8888.*LISTEN'; do true; done

